In [2]:
print("abc")

abc

In [3]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\desktop\python-learning-kmc\env\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\dell\desktop\python-learning-kmc\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.7 MB 3.1 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/9.7 MB 5.0 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.7 MB 5.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.7 MB 5.4 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.7 MB 5.9 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.7 MB 5.2 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.7 MB 4.7 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 5.0 MB/s  0:00:02
Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.3 MB 9.9 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.3 MB 10.7 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.3 MB 11.2 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.3 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 11.0 MB/s  0:00:01
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.4 pandas-3.0.2 tzdata-2026.2

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
#creating series from list
data = [1,2,3,4,5]
series = pd.Series(data)
#print series
series #--> last line aafai print hunxa mathi print garda print lekhnai parxa okay

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
# custom index
marks = pd.Series([90,80,70], index=['Maths', 'Science', 'English'])
marks

Maths      90
Science    80
English    70
dtype: int64

In [7]:
print(marks['Maths']) #accessing value using index label

90

In [8]:
# creating series from dictionary
data_dict = {'a': 90, 'b': 80, 'c': 70}
series_dict = pd.Series(data_dict)
series_dict

a    90
b    80
c    70
dtype: int64

In [ ]:
# creating scalar data
series = pd.Series(5, index=['Ram', 'Shyam', 'Gita']) # sabbai index lai eutai value dinu parey scalar use hunxa
series

Ram      5
Shyam    5
Gita     5
dtype: int64

In [10]:
#Accessing Series data
marks = pd.Series([80,85,90], index=['Ram', 'Shyam', 'Gita'])
print(marks.iloc[0]) #accessing value using integer position

80

In [11]:
# access by label
print(marks['Ram']) #accessing value using index label"

80

In [12]:
# Series Real Example
stock_prices = pd.Series([157, 156, 143,123,567], index=['Monday', 'Tuesday','Wednesday', 'Thursday','Friday'])
stock_prices

Monday       157
Tuesday      156
Wednesday    143
Thursday     123
Friday       567
dtype: int64

In [14]:
print(stock_prices['Tuesday'])

156

In [15]:
print(stock_prices.mean())

229.2

In [16]:
print(stock_prices.min())

123

In [17]:
print(stock_prices.max())

567

In [21]:
print(stock_prices[stock_prices > 150])

Monday     157
Tuesday    156
Friday     567
dtype: int64

In [22]:
print(stock_prices > 150)

Monday        True
Tuesday       True
Wednesday    False
Thursday     False
Friday        True
dtype: bool

In [23]:
#DataFrame with two-dimensional data with rows and columns
data={
    'Name' : ["Alice", "JON" , "sham"],
    'Age' : [20,20,40],
    'City': [ 'NewYork', 'LosANGLES', 'MNR']
}

In [24]:
df = pd.DataFrame(data)
print(df)

    Name  Age       City
0  Alice   20    NewYork
1    JON   20  LosANGLES
2   sham   40        MNR

In [ ]:
df.head(1) # mathi bata data herna

    Name  Age     City
0  Alice   20  NewYork

In [ ]:
df.tail(1)# tala bata ko 1st value show  garxa

   Name  Age City
2  sham   40  MNR

In [ ]:
df.shape # rows and column count garera dekhauxa

(3, 3)

In [ ]:
df.columns # only column haaru lai specify garna

Index(['Name', 'Age', 'City'], dtype='str')

In [29]:
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [31]:
df.describe()

             Age
count   3.000000
mean   26.666667
std    11.547005
min    20.000000
25%    20.000000
50%    20.000000
75%    30.000000
max    40.000000

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [33]:
df['Name']

0    Alice
1      JON
2     sham
Name: Name, dtype: str

In [34]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [37]:
df[['Name','Age']]

    Name  Age
0  Alice   20
1    JON   20
2   sham   40

In [38]:
df.iloc[0]

Name      Alice
Age          20
City    NewYork
Name: 0, dtype: object

In [40]:
# Filtering DATAFRAME
filtered_df=df[df['Age']>28]
print(filtered_df)

   Name  Age City
2  sham   40  MNR

In [44]:
# Multiple Conditions
filtered_df = df[(df['Age']>15) & (df['City']== 'NewYork')]
print(filtered_df)

    Name  Age     City
0  Alice   20  NewYork

In [45]:
# Multiple Conditions
filtered_df = df[(df['Age']>15) | (df['City']== 'NewYork')]
print(filtered_df)

    Name  Age       City
0  Alice   20    NewYork
1    JON   20  LosANGLES
2   sham   40        MNR

In [46]:
# Crud Add , Update , Delete
# ADDing a new column
df['Salary'] = [5000, 6000, 7000]
print(df)

    Name  Age       City  Salary
0  Alice   20    NewYork    5000
1    JON   20  LosANGLES    6000
2   sham   40        MNR    7000

In [47]:
#Updating existing column
df['Salary'] = df['Salary'] + 5000
print(df)

    Name  Age       City  Salary
0  Alice   20    NewYork   10000
1    JON   20  LosANGLES   11000
2   sham   40        MNR   12000

In [48]:
#updating existing column with condition
df.loc[df['Age'] > 30 , 'Salary'] = df['Salary'] +1000
print(df)

    Name  Age       City  Salary
0  Alice   20    NewYork   10000
1    JON   20  LosANGLES   11000
2   sham   40        MNR   13000

In [ ]:
# DEleteing a column
df.drop('Salary' , axis = 1 , inplace = True) ## column wise delete hunxa
print(df)

    Name  Age       City
0  Alice   20    NewYork
1    JON   20  LosANGLES
2   sham   40        MNR

In [50]:
# DEleteing a row
df.drop(0 , axis = 0 , inplace = True) ## row wise delete hunxa
print(df)

   Name  Age       City
1   JON   20  LosANGLES
2  sham   40        MNR

In [51]:
# Read CSV file
df = pd.read_csv('sample_pandas.csv')

In [52]:
print(df)

    first_name  last_name                   company_name  \
0        James       Butt              Benton, John B Jr
1    Josephine    Darakjy          Chanay, Jeffrey A Esq
2          Art     Venere            Chemel, James L Cpa
3        Lenna   Paprocki         Feltz Printing Service
4      Donette     Foller            Printing Dimensions
..         ...        ...                            ...
495    Brittni  Gillaspie                    Inner Label
496    Raylene      Kampa                     Hermar Inc
497        Flo   Bookamer   Simonton Howe & Schneider Pc
498       Jani      Biddy  Warehouse Office & Paper Prod
499   Chauncey     Motley     Affiliated With Travelodge

                  address        city      county state    zip        phone1  \
0      6649 N Blue Gum St         NaN     Orleans    LA  70116  504-621-8927
1     4 B Blue Ridge Blvd    Brighton  Livingston    MI  48116  810-292-9388
2    8 W Cerritos Ave #54  Bridgeport  Gloucester    NJ   8014  856-636-8749
3             639 Main St   Anchorage   Anchorage    AK  99501  907-385-4412
4            34 Center St    Hamilton      Butler    OH  45011  513-570-1893
..                    ...         ...         ...   ...    ...           ...
495            67 Rv Cent       Boise         Ada    ID  83709  208-709-1235
496        2 Sw Nyberg Rd     Elkhart     Elkhart    IN  46514  574-499-1454
497       89992 E 15th St    Alliance   Box Butte    NE  69301  308-726-2182
498      61556 W 20th Ave     Seattle        King    WA  98104  206-711-6498
499        63 E Aurora Dr     Orlando      Orange    FL  32804  407-413-4842

           phone2                          email  \
0    504-845-1427                jbutt@gmail.com
1    810-374-9840  josephine_darakjy@darakjy.org
2    856-264-4130                 art@venere.org
3    907-921-2010          lpaprocki@hotmail.com
4    513-549-4561         donette.foller@cox.net
..            ...                            ...
495  208-206-9848       bgillaspie@gillaspie.com
496  574-330-1884               rkampa@kampa.org
497  308-250-6987           flo.bookamer@cox.net
498  206-395-6284               jbiddy@yahoo.com
499  407-557-8857        chauncey_motley@aol.com

                                         web
0               http://www.bentonjohnbjr.com
1           http://www.chanayjeffreyaesq.com
2             http://www.chemeljameslcpa.com
3        http://www.feltzprintingservice.com
4          http://www.printingdimensions.com
..                                       ...
495                http://www.innerlabel.com
496                 http://www.hermarinc.com
497   http://www.simontonhoweschneiderpc.com
498  http://www.warehouseofficepaperprod.com
499  http://www.affiliatedwithtravelodge.com

[500 rows x 12 columns]

In [ ]:
df.head() # by default 5 lai select garxa if not aru then write inside thhis

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,NaN,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com

In [54]:
df.tail()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
495,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,208-709-1235,208-206-9848,bgillaspie@gillaspie.com,http://www.innerlabel.com
496,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,574-499-1454,574-330-1884,rkampa@kampa.org,http://www.hermarinc.com
497,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,308-726-2182,308-250-6987,flo.bookamer@cox.net,http://www.simontonhoweschneiderpc.com
498,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,206-711-6498,206-395-6284,jbiddy@yahoo.com,http://www.warehouseofficepaperprod.com
499,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,407-413-4842,407-557-8857,chauncey_motley@aol.com,http://www.affiliatedwithtravelodge.com

In [56]:
df.isnull()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,False,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False

In [57]:
df.shape

(500, 12)